### ISSUE TITLE
Error on test

### ISSUE THREAD

**Issue by sbacelar** [JuliaPlots/MakieGallery.jl#23]
I am testing Makie on `Julia 1.1` with a MacBookPro.
I have got the following error:
```
running type_recipe_for_molecule_simulation
ERROR: LoadError: LoadError: KeyError: key "LD_LIBRARY_PATH" not found
```
and finally,
```
in expression starting at worldclim_visualization:4
in expression starting at /Users/myname/.julia/packages/Makie/ogxgz/test/runtests.jl:12
ERROR: Package Makie errored during testing
```

**Comment by SimonDanisch** [comment]
That should be fixed on the newest tag of MakieGallery

**Comment by SimonDanisch** [comment]
Ah, not tagged yet, so fixed on master  ;)

**Comment by sbacelar** [comment]
I updated the package but when I do `test Makie` the same error remains. What shall I do?

**Comment by asinghvi17** [comment]
Try `]add MakieGallery#master` and then testing?







Sincerely,


Anshul Singhvi







On Thu, Mar 14, 2019 at 11:47 AM -0700, "Sérgio Bacelar" <notifications@github.com> wrote:












I updated the package but when I do test Makie the same error remains. What shall I do?

**Comment by sbacelar** [comment]
I added MakieGallery#master and then tested. The results are better but I got:
```
/Users/myname/.julia/packages/Makie/ogxgz/test/test_recordings/line_with_varying_colors: Test Failed at /Users/sergiobacelar/.julia/packages/MakieGallery/lmrcf/src/testruns.jl:107
  Expression: diff <= maxdiff
   Evaluated: 0.057631448755834966 <= 0.03
```
and finally:
```
  /Users/sergiobacelar/.julia/packages/Makie/ogxgz/test/test_recordings/worldclim_visualization                                                               |    1            1
ERROR: LoadError: Some tests did not pass: 184 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /Users/sergiobacelar/.julia/packages/Makie/ogxgz/test/runtests.jl:14
ERROR: Package Makie errored during testing
```

**Comment by asinghvi17** [comment]
Yeah, some of the tests were changed, so we're waiting on new reference images to be generated.







Sincerely,


Anshul Singhvi







On Fri, Mar 15, 2019 at 6:25 AM -0500, "Sérgio Bacelar" <notifications@github.com> wrote:












I added MakieGallery#master and then tested. The results are better but I got:
/Users/myname/.julia/packages/Makie/ogxgz/test/test_recordings/line_with_varying_colors: Test Failed at /Users/sergiobacelar/.julia/packages/MakieGallery/lmrcf/src/testruns.jl:107
  Expression: diff <= maxdiff
   Evaluated: 0.057631448755834966 <= 0.03



and finally:
  /Users/sergiobacelar/.julia/packages/Makie/ogxgz/test/test_recordings/worldclim_visualization                                                               |    1            1
ERROR: LoadError: Some tests did not pass: 184 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /Users/sergiobacelar/.julia/packages/Makie/ogxgz/test/runtests.jl:14
ERROR: Package Makie errored during testing

**Comment by asinghvi17** [comment]
Should be fixed now!
